POST http://127.0.0.1:8000/signup/ 
Content-Type: application/json

{ "username": "msms", "password": "qwertyuiop789!", "email": "qwertyuiop789@gmail.com" }


###
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{ "username": "msms", "password": "qwertyuiop789!" }

###

GET http://127.0.0.1:8000/test_token/
Content-Type: application/json Authorization: token 936c1147c7e9d3d2a9392c57d26c7fbf066ed9f5