# Generated by Django 4.2.5 on 2023-09-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='id',
            new_name='user_id',
        ),
    ]
