# Generated by Django 4.2.5 on 2023-09-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_id_commentlike_user_id_rename_id_post_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='user_id',
            new_name='id',
        ),
    ]
