# Generated by Django 4.2.5 on 2023-09-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
