# Generated by Django 4.2.5 on 2023-09-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='../static/images/default.jpg', upload_to='avatar/'),
        ),
    ]
