# Generated by Django 4.2.5 on 2023-10-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='veryfind',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
