# Generated by Django 4.2.5 on 2023-10-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_veryfind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='veryfind',
            new_name='verified',
        ),
    ]
